on: push
name: Publish
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: install
      uses: docker://node:10.15-alpine
      with:
        entrypoint: npm
        args: ci --production
    - name: generate
      uses: docker://node:10.15-alpine
      with:
        entrypoint: npm
        args: run generate
    - name: push
      uses: docker://node:10.15-alpine
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      with:
        entrypoint: npm
        args: run push
